[versions]
activityCompose = "1.8.1"
androidxAppCompat = "1.6.1"
androidxCompose = "2023.10.01"
androidxKotlinCompiler = "1.5.4"
androidxConstraintLayout = "2.1.4"
androidxCoreKtx = "1.12.0"
androidxNavigation = "2.7.5"
googleMaterial = "1.10.0"
gradle = "8.1.4"
jUnit = "5.9.1"
kotlin = "1.9.20"
lifecycleRuntimeKtx = "2.6.2"
mockk = "1.13.5"

[libraries]
androidX-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidX-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxCompose" }
androidX-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidX-compose-material = { module = "androidx.compose.material:material" }
androidX-compose-material3 = { module = "androidx.compose.material3:material3" }
androidX-compose-ui = { module = "androidx.compose.ui:ui" }
androidX-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidX-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidX-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidX-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidX-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidX-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidxKotlinCompiler" }

androidX-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidX-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }

androidX-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidX-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }

google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

test-jUnit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit" }
test-jUnit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit" }
test-jUnit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }