[versions]
androidxActivityCompose = "1.8.1"
androidxComposeBom = "2023.10.01"
androidxKotlinCompiler = "1.5.4"
androidxActivity = "1.8.1"
androidMaterial = "1.10.0"
gradle = "8.1.4"
kotlin = "1.9.20"
sqldelight = "2.0.0"

[libraries]
## Build Tools
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

## Android
androidX-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }

## Compose
androidX-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }

## UI
android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidX-compose-material3 = { module = "androidx.compose.material3:material3" }
androidX-compose-ui = { module = "androidx.compose.ui:ui" }
androidX-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

## Database
sqldelight = { module = "app.cash.sqldelight:android-driver" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradle" }
androidLibrary = { id = "com.android.library", version.ref = "gradle" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }